// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0kQvMDfMDI9hgdvmiZSSmNFbiBPwk7po',
    appId: '1:409232038702:android:371b8d659b8e2fa72af8bf',
    messagingSenderId: '409232038702',
    projectId: 'echnelapp-2023',
    databaseURL: 'https://echnelapp-2023-default-rtdb.firebaseio.com',
    storageBucket: 'echnelapp-2023.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADaB8yhnzCh5aPYawyZCDH2BtGyh5bU4o',
    appId: '1:409232038702:ios:aa2182e843d938962af8bf',
    messagingSenderId: '409232038702',
    projectId: 'echnelapp-2023',
    databaseURL: 'https://echnelapp-2023-default-rtdb.firebaseio.com',
    storageBucket: 'echnelapp-2023.appspot.com',
    iosClientId: '409232038702-qdj78ejle05l56lsnh3595tb12unplu9.apps.googleusercontent.com',
    iosBundleId: 'com.echnelapp.mp.echnelapp',
  );
}
